---
output: html_document
---

<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 9pt;
  /*line-height: 1;*/
}
h1, h2, h3 ,h4, h5, h6 {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 10pt;
  font-weight: bold;
}
.h1, .h2, .h3, h1, h2, h3 {
  margin-top: 10px;
  margin-bottom: 10px;
}
p {
  margin: 0 0 10px;
  margin-top: 0px;
  margin-right: 0px;
  margin-bottom: 5px;
  margin-left: 0px;
}
hide {
  display: none;
}
</style>

In a nutshell, I would call myself a "pseudo-data scientist". As an engineer at the Electric Reliability Council of Texas (ERCOT)—the independent system operator of the Texas electric grid, my position requires me to not only have expertise with a particular field of study—electric power systems—but also with data processing, analysis, and visualization.

Although every day of work is different for me, most of my tasks involve the following workflow: (1) retrieving data from databases (with R, SQL, or SAS); (2) writing scripts to process the data (with R, python, or VBA); and (3) creating plots (with R, JS, or Excel). My efforts go towards helping my group improve its understanding of real-time events—e.g. transmission faults, generations trips, price spikes.

Outside of work, my biggest passion has always been sports. I actively watch, read, and listen about the NBA (along with some college and international basketball) and the NFL (along with some college football). More recently, I've started following the EPL and Champions League. I still play some sports—softball with co-workers, pick-up hoops or soccer, occasionally, etc.—but, admittedly, I was never all that athletic. (To my credit, at least I am "coordinated" in most things, which comes in handy when playing a random game of ping pong or a round of Top Golf.) Outside of these things, I follow the news in sports betting markets, and I enjoy playing fantasy sports. 

And, on the topic of sports odds and fantasy, since 2012, I've maintained a "database"—really, a couple of spreadsheets and an sqlite database—of game and season-long predictions that me and my two brothers make for the NFL and the NBA. Of course, I've developed code to help me maintain this database. In particular, I've created scripts to scrape schedules, scores, and odds. I'm not completely sure what I'll end up doing with all of this self-maintained data—perhaps an analysis of personal biases—but I think this kind of personal project serves a great (and fun) way to keep myself active with data analysis.

As a life-long sports fan, the opportunity to apply the skills that I've developed to help sports teams achieve success would be a dream come true. I've never completely felt "right" as a power systems engineer. Even though there are plenty of times where I "get" to use my data skills in my current job, there are also plenty of times where I must do more traditional power systems analysis using industry-specific software. The former is what I really enjoy, and the latter is less enjoyable, although necessary, of course.

Over the past three and a half years (since the last semester of my undergraduate education), I've come to believe that my ideal career is as a data scientist. To this end, since the summer of 2018 I've been working towards an analytics degree through the Online Master of Science in Analytics (OMSA) program offered by Georgia Tech. Given my experience with data processing and prior knowledge of machine learning, I've been able to go through the program quickly (towards a graduation date of spring 2020), taking two classes per semester alongside my full-time job. Most importantly (for me), the classes I've taken have re-confirmed my belief that my future lies in data analysis.

What kind of role am I best in (or could be best in)? To be honest, I think I could excel in (and would be happy to work in) several different roles: (1) analyst with a focus on visualization; (2) statistician with a solid understanding of mathematical techniques; (3) machine learning engineer with a focus on tuning models used in production; (4) data engineer with a focus on pre-processing data and building model pipelines. This is not to say that I am highly proficient at each of these roles at the moment, but that I have familiarity with the skills involved in each and could grow to be more proficient when tasked with more specific responsibilities. I like to think of myself as a kind of "T-shaped person", having deep knowledge in one field—electric power systems—but having the capability to adapt to any analytics-related task by applying the data skills that I've developed.
