---
output: html_document
---

<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 8pt;
  /*line-height: 1;*/
}
h1, h2, h3 ,h4, h5, h6 {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 10pt;
  font-weight: bold;
}
.h1, .h2, .h3, h1, h2, h3 {
  margin-top: 10px;
  margin-bottom: 10px;
}
p {
  margin: 0 0 10px;
  margin-top: 0px;
  margin-right: 0px;
  margin-bottom: 5px;
  margin-left: 0px;
}
</style>

**Anthony (Tony) ElHabr** *anthonyelhabr@gmail.com*

## Education

### M.S. Analytics (Analytics Track), Spring 2020, Georgia Institute of Technology, GPA: 3.5/4

*Working towards degree (2 classes per semester) while working full-time.*

+ *Notable Classes:* Discrete Optimization, Simulation, Regression Analysis, Time Series Analysis, Data and Visual Analytics

### B.S. Electrical Engineering (Power Systems Track), May 2016, The University of Texas at Austin, GPA: 3.85/4

+ *Honors & Societies:* Engineering Honors Program Member, Virginia & Ernest Cockrell, Jr. Scholarship Recipient; Officer/Member of IEEE Power and Energy Society UT Student Branch

+ *Work Experience:* Teaching Assistant, EE438: Electronics Circuits (Spring 2016); Academic Tutor, multiple Engineering classes (2016)

## Skills & Abilities

**SOFTWARE**

+ *Advanced:* R, VBA (for Excel), SQL (Oracle), Windows OS, Microsoft Office Suite, PowerWorld, PSSE

+ *Intermediate:* python, SAS, OsiSoft PiSeeq, JavaScript (Plotly and D3), HTML/CSS, git, C#, ASP.NET Web Framework

+ *Used:* C/C++, x86 assembly language, MATLAB 

## ERCOT Experience

**OPERATIONS ENGINEER II, OPERATIONS PLANNING (GRID ANALYSIS) | ERCOT | 12/2018 - present**

+ Develop tools and procedures to monitor transmission and generator events on the grid in real-time and up to 90 days in the future.

***Major Projects & Responsibilities:***

+ *Trend Analysis Tool*: Assist with development and maintenance of internal web-based BI dashboards for analyzing daily market and operational information.

+ *Voltage Profile Seasonal Studies:* Conduct seasonal studies coordinated with Transmission Service Providers (TSPs) to define generator voltage setpoints.

+ *N-1-1 Tool:* Developed high performance power flow tool to evaluate N-1-1 contingencies on a daily basis.

**MARKET OPERATIONS ENGINEER II, CONGESTION REVENUE RIGHTS (CRR) | ERCOT | 6/2017 - 12/2018**

+ Prepared data for CRR auctions (about twice a month), and validated and analyzed results.

***Studies:***

+ *Price Convergence:* Evaluated correlations among settlement point prices across CRR, DAM, and Real-Time Market (DAM). Created price contour maps for illustrative purposes.

+ *Bidding Behavior:* Studied popularity of "penny bids", fixed hedges, and portfolio diversity among CRR participants.

+ *CRR Validation:* Led group of CRR and Market Analysis team members in developing automated SAS tool (set of programs) to perform checks of CRR optimization output.

**CO-FOUNDER/CO-LEADER, ERCOT DATA SCIENCE GROUP | ERCOT | 9/2017 - present day (19 meetings total)**

+ Schedule speakers for periodic meetings of an internal group that discusses data science concepts and their implementation.

+ Personally given 4 presentations: (1) R and the "tidyverse"; (2) logistic regression; (3) live-coding of solutions assigned exercises; (4) SQL tips and tricks.

**ENGINEERING DEVELOPMENT PROGRAM (EDP) ENGINEER | ERCOT | 7/2016 - 5/2017**

+ Completed 12-month program to provide entry-level engineers with skills for becoming successful in power industry.

***Projects:***

+ *5 - Minute Resolution Wind Forecast Analysis:* Evaluated proposed auto-regressive (AR) model for Multi-Interval Real-Time Market (MIRTM) and analyzed accuracy of third-party vendor's forecasts.

+ *Daily Market Summary Template Improvements:* Revised existing real-time (RT) and day-ahead market-(DAM) SQL queries to facilitate execution on separate database and re-factored VBA code to improve readability and consistency.

## Pre-ERCOT Experience

**INSTRUMENTATION ENGINEERING INTERN | EXXONMOBIL | 05/2015 - 08/2015**

**MONITORING & DIAGNOSTICS SYSTEMS SUPPORT INTERN | LUMINANT | 05/2014 - 08/2014**

**ELECTRIC DISTRIBUTION PLANNING & COMPUTER SUPPORT CO-OP | CENTERPOINT| 01/2014 - 05/2014**
