---
output: html_document
---

<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 9pt;
  /*line-height: 1;*/
}
h1, h2, h3 ,h4, h5, h6 {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 10pt;
  font-weight: bold;
}
.h1, .h2, .h3, h1, h2, h3 {
  margin-top: 10px;
  margin-bottom: 10px;
}
p {
  margin: 0 0 10px;
  margin-top: 0px;
  margin-right: 0px;
  margin-bottom: 5px;
  margin-left: 0px;
}
hide {
  display: none;
}
</style>

**Anthony (Tony) ElHabr**  --- anthonyelhabr@gmail.com --- [tonyelhabr.rbind.io](https://tonyelhabr.rbind.io/)

## Education

### M.S. Analytics (Analytics Track), Spring 2020, Georgia Institute of Technology, GPA: 3.5/4

*Working towards degree (2 classes per semester) while working full-time.*

+ *Notable Classes:* Discrete Optimization, Simulation, Regression Analysis, Time Series Analysis, Data and Visual Analytics

### B.S. Electrical Engineering (Power Systems Track), May 2016, The University of Texas at Austin, GPA: 3.85/4

+ *Honors & Societies:* Engineering Honors Program Member, Cockrell Scholarship Recipient; Officer/Member of IEEE Power and Energy Society Student Branch

+ *Work Experience:* Teaching Assistant, Electronics Circuits (Spring 2016); Academic Tutor, multiple Engineering classes (2016)

## Skills & Abilities

**SOFTWARE**

+ *Advanced:* R, SQL (Oracle), VBA (for Excel), Windows OS, Microsoft Office Suite

+ *Intermediate:* python, SAS, JavaScript (Plotly and D3), HTML/CSS, git, C#, ASP.NET Web Framework

+ *Other:* C/C++, x86 assembly language, MATLAB, UPLAN

## Electric Reliability Council of Texas (ERCOT) Experience (Energy Industry)

**OPERATIONS ENGINEER II, OPERATIONS PLANNING (GRID ANALYSIS) | ERCOT | 12/2018 - present**

Develop tools and procedures to monitor transmission and generator events on the grid in real-time and up to 90 days in the future.

***Projects & Responsibilities:***

+ *Trend Analysis Tool:* Assist with development and maintenance of internal web-based BI dashboards for analyzing daily market and operational information.

+ *Voltage Profile Seasonal Studies:* Conduct seasonal studies coordinated with Transmission Service Providers (TSPs) to define generator voltage setpoints.

+ *N-1-1 Tool:* Developed scripts for high performance power flow tool to evaluate N-1-1 contingencies on a daily basis.

+ *2019 Summer Analysis:* Gathered data and created visuals for outages and ancillary services in review of 2019 summer.

**MARKET OPERATIONS ENGINEER II, CONGESTION REVENUE RIGHTS (CRR) | ERCOT | 6/2017 - 12/2018**

Prepared data for CRR auctions (about twice a month), and validated and analyzed results.

***Projects/Studies:***

+ *Price Convergence:* Evaluated correlations among settlement point prices across markets. Created price contour maps for illustrative purposes.

+ *Bidding Behavior:* Studied popularity of “penny bids”, fixed hedges, and portfolio diversity among CRR participants.

+ *CRR Validation:* Led group in developing automated SAS tool to perform checks of CRR optimization output.

**ENGINEERING DEVELOPMENT PROGRAM (EDP) ENGINEER | ERCOT | 7/2016 - 5/2017**

Completed 12-month program to provide entry-level engineers with skills for becoming successful in power industry.

***Projects:***

+ *NOX Emissions Sensitivity Analysis:* Evaluated impact of varying NOX emission allowance costs on generation dispatch using UPLAN.

+ *5 - Minute Resolution Wind Forecast Analysis:* Evaluated proposed auto-regressive (AR) model for Multi-Interval Real-Time Market (MIRTM) and analyzed accuracy of third-party vendor's forecasts.

+ *Daily Market Summary Template Improvements:* Revised existing real-time (RT) and day-ahead market-(DAM) SQL queries to facilitate execution on separate database and re-factored VBA code to improve readability and consistency.


**CO-FOUNDER/LEADER, ERCOT DATA SCIENCE GROUP | ERCOT | 9/2017 - present day (19 meetings total)**

+ Schedule speakers for periodic meetings of an internal group that discusses data science concepts and their implementation.

+ Personally given 4 presentations: (1) R and the "tidyverse"; (2) logistic regression; (3) live-coding of assigned exercises; (4) SQL tips.

**Undergraduate Internship Experience**

+ Instrumentation Engineering Intern, ExxonMobil

+ Monitoring & Diagnostics Systems Support Intern, Luminant

+ Electric Distribution Planning & Computer Support Co-op, CenterPoint
